In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
dataset = pd.read_csv('kt1.csv')
testset = pd.read_csv('kaggletest.csv')

In [3]:
dataset.head()

,ID,Age,BusinessTravel,DailyRate,Department,DistanceFromHome,Gender,HourlyRate,JobInvolvement,JobLevel,...,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,WorkLifeBalance,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,FormalWarnings,ProjectsContributed,Attrition
0,1,44.0,Travel_Rarely,1376.0,Human Resources,1,Male,91.0,2.0,3,...,1,1098,2.0,3.0,6,3.0,6,0,15.0,1
1,2,25.0,Non-Travel,675.0,Research & Development,5,Male,85.0,4.0,2,...,1,369,2.0,3.0,3,1.0,5,0,7.0,0
2,3,57.0,Travel_Rarely,210.0,Sales,29,Male,56.0,2.0,4,...,1,568,1.0,2.0,0,0.0,0,0,3.0,0
3,4,47.0,Travel_Rarely,1180.0,Research & Development,25,Male,84.0,3.0,3,...,1,1993,1.0,3.0,14,12.0,11,0,14.0,0
4,5,22.0,Travel_Rarely,391.0,Research & Development,7,Male,75.0,3.0,1,...,1,1878,4.0,3.0,0,0.0,0,0,5.0,1

In [4]:
dataset.isnull().sum()

ID                          0
Age                         1
BusinessTravel              0
DailyRate                   1
Department                  0
DistanceFromHome            0
Gender                      0
HourlyRate                  2
JobInvolvement              1
JobLevel                    0
JobRole                     0
JobSatisfaction             1
MaritalStatus               0
MonthlyIncome               0
MonthlyRate                 1
NumCompaniesWorked          1
Over18                      0
OverTime                    0
PercentSalaryHike           1
PerformanceRating           0
CommunicationSkill          0
Behaviour                   0
Experience                  0
LvlGrownInOrg               1
ContributionIndex           0
TechnicalExpertise          0
RelationshipSatisfaction    1
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           1
TrainingTimesLastYear       0
Education                   1
EducationField              0
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     1
WorkLifeBalance             1
YearsInCurrentRole          0
YearsSinceLastPromotion     1
YearsWithCurrManager        0
FormalWarnings              0
ProjectsContributed         1
Attrition                   0
dtype: int64

In [5]:
from sklearn.preprocessing import LabelEncoder
for column in dataset.columns:
        if dataset[column].dtype == np.number:
            continue
        dataset[column] = LabelEncoder().fit_transform(dataset[column])
for column in testset.columns:
        if testset[column].dtype == np.number:
            continue
        testset[column] = LabelEncoder().fit_transform(testset[column])

<ipython-input-5-5c89e6c47b49>:3: DeprecationWarning: Converting `np.inexact` or `np.floating` to a dtype is deprecated. The current result is `float64` which is not strictly correct.
  if dataset[column].dtype == np.number:
<ipython-input-5-5c89e6c47b49>:7: DeprecationWarning: Converting `np.inexact` or `np.floating` to a dtype is deprecated. The current result is `float64` which is not strictly correct.
  if testset[column].dtype == np.number:

In [26]:
ds = dataset[['ID','Age','Attrition','CommunicationSkill','Department','DistanceFromHome','Education','EducationField','EnvironmentSatisfaction','Gender','HourlyRate','JobInvolvement','JobLevel','JobRole','JobSatisfaction','MaritalStatus','MonthlyIncome','MonthlyRate','NumCompaniesWorked','OverTime','Over18','PercentSalaryHike','PerformanceRating','RelationshipSatisfaction','StockOptionLevel','TotalWorkingYears','TrainingTimesLastYear','WorkLifeBalance','YearsInCurrentRole','YearsSinceLastPromotion','YearsWithCurrManager','StandardHours']].copy()
ts = testset[['ID','Age','CommunicationSkill','Department','DistanceFromHome','Education','EducationField','EnvironmentSatisfaction','Gender','HourlyRate','JobInvolvement','JobLevel','JobRole','JobSatisfaction','MaritalStatus','MonthlyIncome','MonthlyRate','NumCompaniesWorked','OverTime','Over18','PercentSalaryHike','PerformanceRating','RelationshipSatisfaction','StockOptionLevel','TotalWorkingYears','TrainingTimesLastYear','WorkLifeBalance','YearsInCurrentRole','YearsSinceLastPromotion','YearsWithCurrManager','StandardHours']].copy()

In [27]:
ds = ds.apply(np.int64)
ts = ts.apply(np.int64)
y = ds['Attrition']
x = ds.drop('Attrition', axis=1)

In [28]:
print(x)

        ID  Age  CommunicationSkill  Department  DistanceFromHome  Education  \
0        0   44                   3           0                 0          2
1        1   25                   4           1                 4          2
2        2   57                   1           2                28          3
3        3   47                   0           1                24          3
4        4   22                   2           1                 6          1
...    ...  ...                 ...         ...               ...        ...
1225  1225   29                   4           1                 6          3
1226  1226   41                   1           1                27          4
1227  1227   36                   2           2                12          5
1228  1228   23                   1           1                 3          3
1229  1229   31                   0           2                25          4

      EducationField  EnvironmentSatisfaction  Gender  HourlyRate  ...  \
0                  3                        2       1          91  ...
1                  1                        2       1          85  ...
2                  2                        1       1          56  ...
3                  3                        1       1          84  ...
4                  1                        4       1          75  ...
...              ...                      ...     ...         ...  ...
1225               5                        2       0          39  ...
1226               1                        1       0          60  ...
1227               2                        2       1          96  ...
1228               3                        1       1          58  ...
1229               2                        1       1          63  ...

      PerformanceRating  RelationshipSatisfaction  StockOptionLevel  \
0                     0                         4                 1
1                     0                         4                 2
2                     0                         3                 1
3                     1                         2                 0
4                     1                         1                 0
...                 ...                       ...               ...
1225                  0                         1                 2
1226                  1                         3                 1
1227                  0                         2                 3
1228                  0                         1                 1
1229                  0                         3                 0

      TotalWorkingYears  TrainingTimesLastYear  WorkLifeBalance  \
0                    24                      1                3
1                     6                      2                3
2                    32                      3                2
3                    25                      3                3
4                     1                      2                3
...                 ...                    ...              ...
1225                 10                      2                3
1226                 21                      3                3
1227                 16                      3                3
1228                  5                      3                4
1229                 10                      4                3

      YearsInCurrentRole  YearsSinceLastPromotion  YearsWithCurrManager  \
0                      6                        3                     6
1                      3                        1                     5
2                      0                        0                     0
3                     14                       12                    11
4                      0                        0                     0
...                  ...                      ...                   ...
1225                   7                        7                     7
1226                   7                        0                    10
1227                   2                        2                     2
1228                   2                        0                     2
1229                   7                        0                     8

      StandardHours
0                 0
1                 0
2                 0
3                 0
4                 0
...             ...
1225              0
1226              0
1227              0
1228              0
1229              0

[1230 rows x 31 columns]

In [29]:
print(y)

0       1
1       0
2       0
3       0
4       1
       ..
1225    1
1226    0
1227    1
1228    0
1229    1
Name: Attrition, Length: 1230, dtype: int64

In [30]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)
#generally we prefer 75:25 ration for train set and test set but since the data here is less i used 80:20 ratio

In [31]:
print(x_train)

        ID  Age  CommunicationSkill  Department  DistanceFromHome  Education  \
268    268   37                   3           2                 0          4
1074  1074   29                   0           1                 7          4
406    406   27                   0           1                 1          4
554    554   43                   2           1                 5          3
270    270   29                   2           1                 0          3
...    ...  ...                 ...         ...               ...        ...
763    763   33                   0           1                24          3
835    835   28                   1           1                 1          4
1216  1216   38                   4           2                 0          4
559    559   46                   4           2                 1          3
684    684   25                   3           2                 7          3

      EducationField  EnvironmentSatisfaction  Gender  HourlyRate  ...  \
268                3                        3       1          31  ...
1074               4                        2       1          77  ...
406                1                        1       0          47  ...
554                3                        1       0          81  ...
270                1                        4       0          87  ...
...              ...                      ...     ...         ...  ...
763                3                        1       1          55  ...
835                3                        3       1          46  ...
1216               1                        4       1          86  ...
559                1                        3       1          74  ...
684                1                        4       1          57  ...

      PerformanceRating  RelationshipSatisfaction  StockOptionLevel  \
268                   0                         3                 2
1074                  0                         4                 0
406                   0                         2                 1
554                   0                         4                 0
270                   0                         2                 2
...                 ...                       ...               ...
763                   1                         2                 0
835                   0                         4                 0
1216                  0                         1                 2
559                   0                         2                 1
684                   1                         3                 1

      TotalWorkingYears  TrainingTimesLastYear  WorkLifeBalance  \
268                   6                      2                2
1074                  7                      4                2
406                   4                      2                3
554                  21                      2                3
270                   9                      2                2
...                 ...                    ...              ...
763                   5                      0                3
835                   5                      3                2
1216                 16                      3                3
559                  13                      5                2
684                   4                      4                3

      YearsInCurrentRole  YearsSinceLastPromotion  YearsWithCurrManager  \
268                    3                        1                     3
1074                   7                        0                     7
406                    2                        2                     2
554                   12                        6                    14
270                    7                        1                     7
...                  ...                      ...                   ...
763                    2                        2                     2
835                    2                        2                     1
1216                  13                        5                     8
559                    6                        0                     3
684                    2                        1                     2

      StandardHours
268               0
1074              0
406               0
554               0
270               0
...             ...
763               0
835               0
1216              0
559               0
684               0

[984 rows x 31 columns]

In [32]:
print(y_train)

268     0
1074    1
406     0
554     0
270     0
       ..
763     1
835     1
1216    0
559     0
684     0
Name: Attrition, Length: 984, dtype: int64

In [33]:
print(x_test)

        ID  Age  CommunicationSkill  Department  DistanceFromHome  Education  \
18      18   35                   4           1                15          3
342    342   27                   4           1                13          3
467    467   41                   1           1                 0          3
1205  1205   43                   4           1                 0          3
858    858   41                   0           1                 4          2
...    ...  ...                 ...         ...               ...        ...
649    649   33                   3           1                 0          5
716    716   40                   2           1                15          4
427    427   30                   2           1                 1          4
818    818   47                   3           1                13          4
899    899   23                   1           1                19          1

      EducationField  EnvironmentSatisfaction  Gender  HourlyRate  ...  \
18                 1                        4       0          91  ...
342                1                        1       1          42  ...
467                1                        4       1          76  ...
1205               1                        4       0          33  ...
858                1                        1       1          95  ...
...              ...                      ...     ...         ...  ...
649                3                        1       0          95  ...
716                3                        1       1          51  ...
427                5                        4       0          78  ...
818                5                        3       1          64  ...
899                1                        1       1          97  ...

      PerformanceRating  RelationshipSatisfaction  StockOptionLevel  \
18                    0                         4                 0
342                   0                         4                 2
467                   1                         1                 1
1205                  0                         2                 1
858                   0                         1                 1
...                 ...                       ...               ...
649                   0                         3                 1
716                   0                         4                 0
427                   0                         4                 0
818                   0                         3                 1
899                   0                         2                 0

      TotalWorkingYears  TrainingTimesLastYear  WorkLifeBalance  \
18                   11                      3                1
342                   9                      3                2
467                  12                      3                3
1205                 12                      2                2
858                   5                      2                1
...                 ...                    ...              ...
649                  10                      2                3
716                  10                      6                3
427                  10                      2                3
818                  16                      4                4
899                   5                      2                3

      YearsInCurrentRole  YearsSinceLastPromotion  YearsWithCurrManager  \
18                     8                        3                     3
342                    7                        6                     8
467                    3                        1                     0
1205                   2                        2                     2
858                    0                        0                     0
...                  ...                      ...                   ...
649                    1                        0                     5
716                    0                        0                     0
427                    7                        0                     7
818                    7                        1                     7
899                    3                        1                     2

      StandardHours
18                0
342               0
467               0
1205              0
858               0
...             ...
649               0
716               0
427               0
818               0
899               0

[246 rows x 31 columns]

In [34]:
print(y_test)

18      0
342     0
467     0
1205    0
858     1
       ..
649     0
716     0
427     0
818     0
899     0
Name: Attrition, Length: 246, dtype: int64

In [35]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [36]:
print(x_train)

[[-0.94917413  0.03189505  0.58819813 ...  0.03189505 -0.31355581
   0.        ]
 [ 1.30650947  0.03189505 -1.53709058 ...  0.03189505  0.79729537
   0.        ]
 [-0.56296528  0.03189505 -1.53709058 ...  0.03189505 -0.5912686
   0.        ]
 ...
 [ 1.70391279  0.03189505  1.2966277  ...  0.03189505  1.07500817
   0.        ]
 [-0.1347772   0.03189505  1.2966277  ...  0.03189505 -0.31355581
   0.        ]
 [ 0.21504966  0.03189505  0.58819813 ...  0.03189505 -0.5912686
   0.        ]]

In [37]:
print(x_test)

[[-1.64882786  0.03189505  1.2966277  ...  0.03189505 -0.31355581
   0.        ]
 [-0.74207663  0.03189505  1.2966277  ...  0.03189505  1.07500817
   0.        ]
 [-0.39224977  0.03189505 -0.82866101 ...  0.03189505 -1.14669419
   0.        ]
 ...
 [-0.50419436  0.03189505 -0.12023144 ...  0.03189505  0.79729537
   0.        ]
 [ 0.59006406  0.03189505  0.58819813 ...  0.03189505  0.79729537
   0.        ]
 [ 0.81675187  0.03189505 -0.82866101 ...  0.03189505 -0.5912686
   0.        ]]

In [38]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0 , probability=True)
classifier.fit(x_train,y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=True, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

In [39]:
y_pred = classifier.predict(x_test)

In [40]:
print(y_pred)

[0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]

In [41]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)
acc =  accuracy_score(y_test,y_pred)
print("Accuracy Score =",acc*100,"%")

[[210   1]
 [ 34   1]]
Accuracy Score = 85.77235772357723 %

In [42]:
y_pred2 = classifier.predict_proba(ts)

In [43]:
print(y_pred2)

[[8.29723980e-01 1.70276020e-01]
 [8.48184213e-01 1.51815787e-01]
 [8.48179782e-01 1.51820218e-01]
 [8.40771528e-01 1.59228472e-01]
 [8.47121517e-01 1.52878483e-01]
 [8.56498616e-01 1.43501384e-01]
 [8.38998216e-01 1.61001784e-01]
 [8.41551203e-01 1.58448797e-01]
 [8.58266854e-01 1.41733146e-01]
 [8.37995776e-01 1.62004224e-01]
 [8.46093880e-01 1.53906120e-01]
 [8.56591989e-01 1.43408011e-01]
 [8.49853468e-01 1.50146532e-01]
 [8.47846425e-01 1.52153575e-01]
 [8.51514957e-01 1.48485043e-01]
 [8.28850986e-01 1.71149014e-01]
 [8.45901159e-01 1.54098841e-01]
 [8.59273240e-01 1.40726760e-01]
 [8.48500233e-01 1.51499767e-01]
 [8.28765177e-01 1.71234823e-01]
 [8.49823583e-01 1.50176417e-01]
 [8.49398369e-01 1.50601631e-01]
 [8.45641739e-01 1.54358261e-01]
 [8.47464614e-01 1.52535386e-01]
 [8.57775190e-01 1.42224810e-01]
 [8.37261647e-01 1.62738353e-01]
 [8.38094743e-01 1.61905257e-01]
 [8.47738755e-01 1.52261245e-01]
 [8.28976009e-01 1.71023991e-01]
 [8.39188143e-01 1.60811857e-01]
 [8.47023586e-01 1.52976414e-01]
 [8.27954242e-01 1.72045758e-01]
 [8.47665333e-01 1.52334667e-01]
 [8.37083283e-01 1.62916717e-01]
 [8.59230513e-01 1.40769487e-01]
 [8.46786665e-01 1.53213335e-01]
 [8.51142850e-01 1.48857150e-01]
 [8.39839743e-01 1.60160257e-01]
 [8.50066819e-01 1.49933181e-01]
 [8.49317154e-01 1.50682846e-01]
 [8.51039031e-01 1.48960969e-01]
 [8.50652958e-01 1.49347042e-01]
 [8.36803528e-01 1.63196472e-01]
 [8.58766767e-01 1.41233233e-01]
 [8.59478688e-01 1.40521312e-01]
 [8.36579239e-01 1.63420761e-01]
 [8.46044391e-01 1.53955609e-01]
 [8.46031671e-01 1.53968329e-01]
 [8.54889622e-01 1.45110378e-01]
 [8.39677129e-01 1.60322871e-01]
 [8.49984880e-01 1.50015120e-01]
 [8.57275880e-01 1.42724120e-01]
 [8.31734502e-01 1.68265498e-01]
 [8.56209308e-01 1.43790692e-01]
 [8.57596855e-01 1.42403145e-01]
 [8.36436447e-01 1.63563553e-01]
 [8.59569188e-01 1.40430812e-01]
 [8.39055546e-01 1.60944454e-01]
 [8.48946403e-01 1.51053597e-01]
 [8.42553125e-01 1.57446875e-01]
 [8.66227968e-01 1.33772032e-01]
 [8.29993029e-01 1.70006971e-01]
 [8.37085273e-01 1.62914727e-01]
 [8.50606309e-01 1.49393691e-01]
 [8.42070565e-01 1.57929435e-01]
 [8.28831313e-01 1.71168687e-01]
 [8.57139703e-01 1.42860297e-01]
 [8.39865066e-01 1.60134934e-01]
 [8.59193683e-01 1.40806317e-01]
 [8.47956545e-01 1.52043455e-01]
 [8.50536752e-01 1.49463248e-01]
 [8.26806414e-01 1.73193586e-01]
 [8.41612952e-01 1.58387048e-01]
 [8.57713354e-01 1.42286646e-01]
 [8.38844377e-01 1.61155623e-01]
 [8.65388576e-01 1.34611424e-01]
 [8.27984210e-01 1.72015790e-01]
 [8.48769035e-01 1.51230965e-01]
 [8.55082448e-01 1.44917552e-01]
 [8.45239263e-01 1.54760737e-01]
 [8.38357843e-01 1.61642157e-01]
 [8.57589863e-01 1.42410137e-01]
 [8.46089072e-01 1.53910928e-01]
 [8.49805426e-01 1.50194574e-01]
 [8.50644658e-01 1.49355342e-01]
 [8.41234109e-01 1.58765891e-01]
 [8.66185898e-01 1.33814102e-01]
 [8.47512445e-01 1.52487555e-01]
 [8.51010291e-01 1.48989709e-01]
 [8.50173013e-01 1.49826987e-01]
 [8.50044151e-01 1.49955849e-01]
 [9.99999900e-01 1.00000010e-07]
 [8.54155037e-01 1.45844963e-01]
 [8.36727792e-01 1.63272208e-01]
 [8.31797738e-01 1.68202262e-01]
 [8.27123487e-01 1.72876513e-01]
 [8.39021889e-01 1.60978111e-01]
 [8.58908283e-01 1.41091717e-01]
 [8.45519015e-01 1.54480985e-01]
 [8.58772983e-01 1.41227017e-01]
 [8.49932025e-01 1.50067975e-01]
 [8.37535384e-01 1.62464616e-01]
 [8.58687174e-01 1.41312826e-01]
 [8.49723763e-01 1.50276237e-01]
 [8.55832098e-01 1.44167902e-01]
 [8.27804946e-01 1.72195054e-01]
 [8.59478491e-01 1.40521509e-01]
 [8.57554441e-01 1.42445559e-01]
 [8.45958905e-01 1.54041095e-01]
 [8.59268047e-01 1.40731953e-01]
 [8.28291862e-01 1.71708138e-01]
 [8.30303701e-01 1.69696299e-01]
 [8.50114956e-01 1.49885044e-01]
 [8.36527927e-01 1.63472073e-01]
 [8.50339134e-01 1.49660866e-01]
 [8.46592677e-01 1.53407323e-01]
 [8.39751652e-01 1.60248348e-01]
 [8.46174587e-01 1.53825413e-01]
 [8.29016582e-01 1.70983418e-01]
 [8.58951061e-01 1.41048939e-01]
 [8.47066400e-01 1.52933600e-01]
 [8.36292592e-01 1.63707408e-01]
 [8.56298970e-01 1.43701030e-01]
 [8.57599064e-01 1.42400936e-01]
 [8.39047307e-01 1.60952693e-01]
 [8.37428359e-01 1.62571641e-01]
 [8.50193044e-01 1.49806956e-01]
 [8.48090037e-01 1.51909963e-01]
 [8.37618329e-01 1.62381671e-01]
 [8.37274239e-01 1.62725761e-01]
 [8.39330261e-01 1.60669739e-01]
 [8.45940384e-01 1.54059616e-01]
 [8.55165887e-01 1.44834113e-01]
 [8.31048424e-01 1.68951576e-01]
 [8.54040536e-01 1.45959464e-01]
 [8.45919095e-01 1.54080905e-01]
 [8.41434696e-01 1.58565304e-01]
 [8.46359997e-01 1.53640003e-01]
 [8.41423152e-01 1.58576848e-01]
 [8.46940807e-01 1.53059193e-01]
 [8.57099038e-01 1.42900962e-01]
 [8.49325171e-01 1.50674829e-01]
 [8.45487437e-01 1.54512563e-01]
 [8.46516267e-01 1.53483733e-01]
 [8.58516017e-01 1.41483983e-01]
 [8.58265531e-01 1.41734469e-01]
 [8.49216697e-01 1.50783303e-01]
 [8.37158144e-01 1.62841856e-01]
 [8.46425637e-01 1.53574363e-01]
 [8.56994491e-01 1.43005509e-01]
 [8.56196749e-01 1.43803251e-01]
 [8.48156956e-01 1.51843044e-01]
 [8.58110867e-01 1.41889133e-01]
 [8.62395476e-01 1.37604524e-01]
 [8.56135919e-01 1.43864081e-01]
 [8.40615156e-01 1.59384844e-01]
 [8.47506698e-01 1.52493302e-01]
 [8.40715756e-01 1.59284244e-01]
 [8.45566629e-01 1.54433371e-01]
 [8.53558229e-01 1.46441771e-01]
 [8.63371552e-01 1.36628448e-01]
 [8.30044823e-01 1.69955177e-01]
 [8.57241539e-01 1.42758461e-01]
 [8.47464595e-01 1.52535405e-01]
 [8.50402824e-01 1.49597176e-01]
 [8.56042954e-01 1.43957046e-01]
 [8.50577861e-01 1.49422139e-01]
 [8.58358938e-01 1.41641062e-01]
 [8.46131203e-01 1.53868797e-01]
 [8.26983060e-01 1.73016940e-01]
 [8.44993519e-01 1.55006481e-01]
 [8.57728413e-01 1.42271587e-01]
 [8.49789864e-01 1.50210136e-01]
 [8.48523662e-01 1.51476338e-01]
 [8.30851804e-01 1.69148196e-01]
 [8.49189158e-01 1.50810842e-01]
 [8.57606579e-01 1.42393421e-01]
 [8.56239092e-01 1.43760908e-01]
 [8.53854073e-01 1.46145927e-01]
 [8.32170116e-01 1.67829884e-01]
 [8.48077164e-01 1.51922836e-01]
 [8.47203683e-01 1.52796317e-01]
 [8.54327807e-01 1.45672193e-01]
 [8.26809444e-01 1.73190556e-01]
 [8.48720227e-01 1.51279773e-01]
 [8.39336548e-01 1.60663452e-01]
 [8.37115169e-01 1.62884831e-01]
 [8.46294981e-01 1.53705019e-01]
 [8.37338051e-01 1.62661949e-01]
 [8.28724548e-01 1.71275452e-01]
 [8.45643704e-01 1.54356296e-01]
 [8.56047100e-01 1.43952900e-01]
 [8.38901261e-01 1.61098739e-01]
 [8.28367871e-01 1.71632129e-01]
 [8.29426812e-01 1.70573188e-01]
 [8.27283149e-01 1.72716851e-01]
 [8.54767798e-01 1.45232202e-01]
 [8.48534417e-01 1.51465583e-01]
 [8.49028289e-01 1.50971711e-01]
 [8.48154821e-01 1.51845179e-01]
 [8.63841098e-01 1.36158902e-01]
 [8.26117787e-01 1.73882213e-01]
 [8.57761323e-01 1.42238677e-01]
 [8.39846870e-01 1.60153130e-01]
 [8.56948760e-01 1.43051240e-01]
 [8.57894444e-01 1.42105556e-01]
 [8.46815595e-01 1.53184405e-01]
 [8.46805296e-01 1.53194704e-01]
 [8.45276852e-01 1.54723148e-01]
 [8.45238250e-01 1.54761750e-01]
 [9.99999900e-01 1.00000010e-07]
 [8.45009313e-01 1.54990687e-01]
 [8.48184393e-01 1.51815607e-01]
 [8.64005152e-01 1.35994848e-01]
 [8.56627578e-01 1.43372422e-01]
 [8.48288508e-01 1.51711492e-01]
 [8.55733797e-01 1.44266203e-01]
 [8.44643963e-01 1.55356037e-01]
 [8.38371480e-01 1.61628520e-01]
 [8.48124993e-01 1.51875007e-01]
 [8.27613251e-01 1.72386749e-01]
 [8.58322601e-01 1.41677399e-01]
 [8.37726803e-01 1.62273197e-01]
 [8.45401638e-01 1.54598362e-01]
 [8.38274357e-01 1.61725643e-01]
 [8.57197095e-01 1.42802905e-01]
 [8.40912876e-01 1.59087124e-01]
 [8.26336422e-01 1.73663578e-01]
 [8.38340504e-01 1.61659496e-01]
 [8.37990449e-01 1.62009551e-01]
 [8.29017232e-01 1.70982768e-01]
 [8.25390112e-01 1.74609888e-01]
 [8.56402445e-01 1.43597555e-01]
 [8.46797589e-01 1.53202411e-01]
 [8.46172209e-01 1.53827791e-01]
 [8.45402892e-01 1.54597108e-01]
 [8.48418848e-01 1.51581152e-01]
 [8.38414521e-01 1.61585479e-01]
 [8.44106263e-01 1.55893737e-01]
 [8.54844703e-01 1.45155297e-01]]

In [44]:
ID =ts['ID']
sub = pd.read_csv('D:\Hackethon\ML Kaggle\Warriors.csv')
sub['ID'] = ID
sub.to_csv('D:\Hackethon\ML Kaggle\Warriors.csv',index=False)

sub = pd.read_csv('D:\Hackethon\ML Kaggle\Warriors.csv')
sub['Attrition'] = y_pred2
sub.to_csv('D:\Hackethon\ML Kaggle\Warriors.csv',index=False)